# .codecov.yml
name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
